/**
 * Cup Clash Trivia — Full Question Bank
 * 50 questions across 4 categories.
 * 20 are randomly selected per session.
 */

export interface TriviaQuestion {
  id: string;
  category: "2026 Tournament" | "History" | "Records" | "Trivia" | "Rules";
  question: string;
  options: [string, string, string, string];
  answer: string;
  explanation: string;
  imagePlaceholder?: string; // will be replaced with real image path
}

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  { id: "q01", category: "2026 Tournament", question: "How many total national teams are competing in the 2026 World Cup?", options: ["32", "40", "48", "64"], answer: "48", explanation: "2026 marks the first time the tournament expanded from 32 to 48 teams.", imagePlaceholder: "/trivia/48-teams.jpg" },
  { id: "q02", category: "2026 Tournament", question: "Which city has been selected to host the 2026 World Cup Final?", options: ["Los Angeles", "Mexico City", "New York / New Jersey (MetLife)", "Toronto"], answer: "New York / New Jersey (MetLife)", explanation: "The final will be held at MetLife Stadium in East Rutherford.", imagePlaceholder: "/trivia/metlife.jpg" },
  { id: "q03", category: "History", question: "Which country is the only one to have participated in every single World Cup?", options: ["Germany", "Brazil", "Italy", "Argentina"], answer: "Brazil", explanation: "Brazil has never missed a World Cup tournament since it started in 1930.", imagePlaceholder: "/trivia/brazil-flag.jpg" },
  { id: "q04", category: "Records", question: "Who is the all-time leading goal scorer in World Cup history?", options: ["Pelé", "Cristiano Ronaldo", "Lionel Messi", "Miroslav Klose"], answer: "Miroslav Klose", explanation: "The German striker holds the record with 16 goals across four tournaments.", imagePlaceholder: "/trivia/klose.jpg" },
  { id: "q05", category: "2026 Tournament", question: "Which stadium is hosting the opening match of the 2026 World Cup?", options: ["SoFi Stadium", "Estadio Azteca", "BC Place", "Hard Rock Stadium"], answer: "Estadio Azteca", explanation: "The legendary Azteca becomes the first stadium to host three opening matches.", imagePlaceholder: "/trivia/azteca.jpg" },
  { id: "q06", category: "Records", question: "Who is the only player to have won three World Cup titles?", options: ["Diego Maradona", "Franz Beckenbauer", "Pelé", "Zinedine Zidane"], answer: "Pelé", explanation: "Pelé won in 1958, 1962, and 1970.", imagePlaceholder: "/trivia/pele.jpg" },
  { id: "q07", category: "2026 Tournament", question: "How many host cities are there across the USA, Canada, and Mexico for 2026?", options: ["12", "16", "20", "10"], answer: "16", explanation: "There are 11 cities in the USA, 3 in Mexico, and 2 in Canada.", imagePlaceholder: "/trivia/host-cities.jpg" },
  { id: "q08", category: "History", question: "In 1986, Diego Maradona scored a goal that became known by what nickname?", options: ["The Hand of God", "The Golden Touch", "The Miracle Strike", "The Argentinian Arrow"], answer: "The Hand of God", explanation: "He scored using his hand against England; the ref did not see it.", imagePlaceholder: "/trivia/maradona.jpg" },
  { id: "q09", category: "2026 Tournament", question: "Due to FIFA's 'Clean Site' rule, what will happen to stadium names like 'SoFi' or 'MetLife'?", options: ["They stay the same", "They are renamed to generic titles", "They are sponsored by Adidas", "They are hidden by flags"], answer: "They are renamed to generic titles", explanation: "FIFA prohibits corporate stadium names during the tournament.", imagePlaceholder: "/trivia/sofi.jpg" },
  { id: "q10", category: "History", question: "Which nation was the first from Africa to ever compete in a World Cup?", options: ["Nigeria", "Cameroon", "Egypt", "Morocco"], answer: "Egypt", explanation: "Egypt debuted in the 1934 tournament held in Italy.", imagePlaceholder: "/trivia/egypt.jpg" },
  { id: "q11", category: "2026 Tournament", question: "Which country is making its first-ever appearance on home soil as a host in 2026?", options: ["USA", "Mexico", "Canada", "None of the above"], answer: "Canada", explanation: "While they have qualified before, this is Canada's first time hosting.", imagePlaceholder: "/trivia/canada.jpg" },
  { id: "q12", category: "History", question: "What was the original name of the World Cup trophy before it was renamed the FIFA World Cup Trophy?", options: ["The Jules Rimet Trophy", "The Stanley Cup", "The Victoria Trophy", "The Golden Globe"], answer: "The Jules Rimet Trophy", explanation: "It was named after the third FIFA President.", imagePlaceholder: "/trivia/rimet.jpg" },
  { id: "q13", category: "2026 Tournament", question: "What new technology is FIFA using for VAR and offside decisions in 2026?", options: ["Drone Cameras", "3D Player Avatars", "Eye-tracking Glasses", "Laser Turf Lines"], answer: "3D Player Avatars", explanation: "Real-time 3D twins of players help make semi-automated decisions faster.", imagePlaceholder: "/trivia/var.jpg" },
  { id: "q14", category: "Records", question: "What is the highest number of goals scored by a single player in one tournament?", options: ["10", "13", "15", "8"], answer: "13", explanation: "Just Fontaine (France) scored 13 goals in the 1958 World Cup.", imagePlaceholder: "/trivia/fontaine.jpg" },
  { id: "q15", category: "History", question: "Which country won the first-ever World Cup in 1930?", options: ["Argentina", "Uruguay", "Brazil", "France"], answer: "Uruguay", explanation: "Uruguay hosted and won the inaugural tournament.", imagePlaceholder: "/trivia/uruguay1930.jpg" },
  { id: "q16", category: "2026 Tournament", question: "What is the maximum number of matches a team will play to win the 2026 trophy?", options: ["7", "8", "9", "10"], answer: "8", explanation: "The expanded format requires 8 games instead of the traditional 7.", imagePlaceholder: "/trivia/bracket2026.jpg" },
  { id: "q17", category: "History", question: "Which player holds the record for most saves in a single World Cup match (16 saves)?", options: ["Manuel Neuer", "Iker Casillas", "Tim Howard", "Gianluigi Buffon"], answer: "Tim Howard", explanation: "Set in 2014 during the USA vs. Belgium Round of 16 match.", imagePlaceholder: "/trivia/timhoward.jpg" },
  { id: "q18", category: "Records", question: "Who is the oldest player to ever score a goal in the World Cup?", options: ["Cristiano Ronaldo", "Roger Milla", "Zlatan Ibrahimovic", "Dino Zoff"], answer: "Roger Milla", explanation: "The Cameroon legend scored at age 42 in 1994.", imagePlaceholder: "/trivia/milla.jpg" },
  { id: "q19", category: "2026 Tournament", question: "Which 2026 host city has the highest altitude, impacting ball flight?", options: ["Denver", "Mexico City", "Guadalajara", "Atlanta"], answer: "Mexico City", explanation: "Estadio Azteca is over 2,200 meters above sea level.", imagePlaceholder: "/trivia/altitude.jpg" },
  { id: "q20", category: "History", question: "Who won the World Cup Golden Boot in 2022?", options: ["Lionel Messi", "Kylian Mbappé", "Luka Modrić", "Harry Kane"], answer: "Kylian Mbappé", explanation: "Mbappé scored 8 goals, including a hat-trick in the final.", imagePlaceholder: "/trivia/mbappe2022.jpg" },
  { id: "q21", category: "Trivia", question: "What animal was the official mascot for the 1966 World Cup?", options: ["A Lion", "A Rooster", "A Dog", "An Armadillo"], answer: "A Lion", explanation: "'World Cup Willie' was the first-ever World Cup mascot.", imagePlaceholder: "/trivia/willie.jpg" },
  { id: "q22", category: "2026 Tournament", question: "Which group stage format was ultimately chosen for 2026?", options: ["16 groups of 3", "12 groups of 4", "8 groups of 6", "10 groups of 5"], answer: "12 groups of 4", explanation: "FIFA changed the plan from 3-team groups to 4-team groups to keep the drama.", imagePlaceholder: "/trivia/groups2026.jpg" },
  { id: "q23", category: "History", question: "Which country hosted the World Cup in 1994?", options: ["USA", "Japan", "Italy", "Mexico"], answer: "USA", explanation: "The 1994 USA tournament still holds the record for highest total attendance.", imagePlaceholder: "/trivia/usa1994.jpg" },
  { id: "q24", category: "Records", question: "Who is the only person to win the World Cup as both a player and a manager twice?", options: ["Didier Deschamps", "Franz Beckenbauer", "Mário Zagallo", "Lionel Scaloni"], answer: "Mário Zagallo", explanation: "The Brazilian legend won as a player in '58/'62 and manager in '70.", imagePlaceholder: "/trivia/zagallo.jpg" },
  { id: "q25", category: "Trivia", question: "Which color was the ball used in the 1966 World Cup final?", options: ["White", "Yellow", "Bright Orange", "Black and White"], answer: "Bright Orange", explanation: "The orange 'Slazenger Challenge' ball was used to help visibility.", imagePlaceholder: "/trivia/ball1966.jpg" },
  { id: "q26", category: "2026 Tournament", question: "What are the mandated 'Hydration Breaks' for the 2026 matches?", options: ["Only if it's 30°C+", "Every 15 minutes", "One 3-minute break per half", "None"], answer: "One 3-minute break per half", explanation: "Due to North American summer heat, breaks are now standard procedure.", imagePlaceholder: "/trivia/heat.jpg" },
  { id: "q27", category: "History", question: "Which nation achieved a historic 'Maracanazo' by beating Brazil at home in 1950?", options: ["Argentina", "Uruguay", "Germany", "Sweden"], answer: "Uruguay", explanation: "Uruguay's victory in the final match silenced 200,000 fans in the Maracanã.", imagePlaceholder: "/trivia/maracanazo.jpg" },
  { id: "q28", category: "Records", question: "Which team holds the record for the most red cards in a single World Cup match?", options: ["Netherlands", "Portugal", "Both", "Italy"], answer: "Both", explanation: "The 'Battle of Nuremberg' in 2006 saw 4 red cards between these two teams.", imagePlaceholder: "/trivia/nuremberg.jpg" },
  { id: "q29", category: "Trivia", question: "What is the name of the dog who famously found the stolen Jules Rimet trophy in 1966?", options: ["Buddy", "Pickles", "Rover", "Lucky"], answer: "Pickles", explanation: "Pickles found the trophy wrapped in newspaper in a garden hedge.", imagePlaceholder: "/trivia/pickles.jpg" },
  { id: "q30", category: "2026 Tournament", question: "Which city will host the most total matches (9) in the 2026 tournament?", options: ["Dallas (Arlington)", "Atlanta", "Miami", "Mexico City"], answer: "Dallas (Arlington)", explanation: "Dallas was awarded the highest number of matches for the tournament.", imagePlaceholder: "/trivia/dallas.jpg" },
  { id: "q31", category: "History", question: "Who scored the first-ever goal in World Cup history?", options: ["Lucien Laurent", "Guillermo Stábile", "Pelé", "Bert Patenaude"], answer: "Lucien Laurent", explanation: "The Frenchman scored the historic first goal in 1930.", imagePlaceholder: "/trivia/laurent.jpg" },
  { id: "q32", category: "2026 Tournament", question: "What is the Adidas 'Trionda'?", options: ["The official mascot", "The 2026 match ball", "A new goalkeeper glove", "The VAR system"], answer: "The 2026 match ball", explanation: "The Trionda features a revolutionary 4-panel design.", imagePlaceholder: "/trivia/trionda.jpg" },
  { id: "q33", category: "Records", question: "Which nation is the only one to top the FIFA rankings without ever winning a World Cup?", options: ["Belgium", "Netherlands", "Portugal", "USA"], answer: "Belgium", explanation: "Belgium held the #1 spot for years without a tournament title.", imagePlaceholder: "/trivia/belgium.jpg" },
  { id: "q34", category: "History", question: "Which host nation is the only one to be eliminated in the Group Stage?", options: ["South Africa", "Qatar", "Both", "None"], answer: "Both", explanation: "South Africa (2010) and Qatar (2022) both failed to reach the knockouts.", imagePlaceholder: "/trivia/host-exit.jpg" },
  { id: "q35", category: "2026 Tournament", question: "How many teams qualify from each group in the 2026 format?", options: ["Top 1", "Top 2", "Top 2 plus the 8 best 3rd-place teams", "Top 3"], answer: "Top 2 plus the 8 best 3rd-place teams", explanation: "This leads to a new Round of 32 knockout stage.", imagePlaceholder: "/trivia/qualify2026.jpg" },
  { id: "q36", category: "Records", question: "Who scored the fastest goal in World Cup history (11 seconds)?", options: ["Hakan Şükür", "Bryan Robson", "Clint Dempsey", "Neymar"], answer: "Hakan Şükür", explanation: "The Turkish striker scored against South Korea just 11 seconds into the 2002 match.", imagePlaceholder: "/trivia/sukur.jpg" },
  { id: "q37", category: "History", question: "Which country won back-to-back World Cups in 1958 and 1962?", options: ["Italy", "Brazil", "Germany", "Argentina"], answer: "Brazil", explanation: "They are the most recent team to successfully defend their title.", imagePlaceholder: "/trivia/brazil5860.jpg" },
  { id: "q38", category: "2026 Tournament", question: "In 2026, which country becomes the first to host the World Cup three different times?", options: ["USA", "Mexico", "Germany", "France"], answer: "Mexico", explanation: "Mexico previously hosted in 1970 and 1986.", imagePlaceholder: "/trivia/mexico3times.jpg" },
  { id: "q39", category: "History", question: "What was the score of the 2014 semi-final between Germany and Brazil?", options: ["2-0", "4-1", "7-1", "5-0"], answer: "7-1", explanation: "Known as 'The Mineirazo', it was Brazil's heaviest World Cup defeat.", imagePlaceholder: "/trivia/mineirazo.jpg" },
  { id: "q40", category: "Records", question: "Lionel Messi holds the record for most World Cup appearances. How many games?", options: ["20", "26", "30", "22"], answer: "26", explanation: "He broke the record during the 2022 World Cup Final.", imagePlaceholder: "/trivia/messi26.jpg" },
  { id: "q41", category: "2026 Tournament", question: "How many stadiums will be used in Canada for the 2026 World Cup?", options: ["2", "3", "5", "1"], answer: "2", explanation: "Toronto (BMO Field) and Vancouver (BC Place) are the two Canadian venues.", imagePlaceholder: "/trivia/canada-venues.jpg" },
  { id: "q42", category: "History", question: "Which African nation became the first to reach a World Cup Semi-Final (2022)?", options: ["Senegal", "Morocco", "Ghana", "Cameroon"], answer: "Morocco", explanation: "Morocco made history in Qatar by reaching the final four.", imagePlaceholder: "/trivia/morocco.jpg" },
  { id: "q43", category: "Trivia", question: "What is the FIFA World Cup trophy actually made of?", options: ["Solid Gold", "18-karat Gold", "Gold-plated Silver", "Polished Brass"], answer: "18-karat Gold", explanation: "It contains 6.1 kilograms of 18-karat gold with a malachite base.", imagePlaceholder: "/trivia/trophy-gold.jpg" },
  { id: "q44", category: "2026 Tournament", question: "Which city will host the US National Team's opening match in 2026?", options: ["Los Angeles", "Seattle", "Miami", "Dallas"], answer: "Los Angeles", explanation: "The USMNT kicks off their campaign at SoFi Stadium.", imagePlaceholder: "/trivia/usmnt.jpg" },
  { id: "q45", category: "Records", question: "Who was the first player to be sent off in a World Cup Final?", options: ["Zinedine Zidane", "Pedro Monzón", "Marcel Desailly", "Frank Rijkaard"], answer: "Pedro Monzón", explanation: "The Argentinian was sent off in the 1990 final against West Germany.", imagePlaceholder: "/trivia/monzon.jpg" },
  { id: "q46", category: "History", question: "What musical instrument was famously banned by FIFA after the 2010 World Cup?", options: ["Drums", "Vuvuzelas", "Trumpets", "Whistles"], answer: "Vuvuzelas", explanation: "The loud plastic horns from South Africa were later restricted.", imagePlaceholder: "/trivia/vuvuzela.jpg" },
  { id: "q47", category: "2026 Tournament", question: "Which 2026 host city is known as 'The 6ix'?", options: ["Vancouver", "Toronto", "Seattle", "Atlanta"], answer: "Toronto", explanation: "Toronto is often referred to by this nickname.", imagePlaceholder: "/trivia/toronto.jpg" },
  { id: "q48", category: "History", question: "In what year was the first World Cup ever broadcast in color on TV?", options: ["1966", "1970", "1974", "1962"], answer: "1970", explanation: "The Mexico 1970 tournament was the first to be seen in color globally.", imagePlaceholder: "/trivia/color-tv.jpg" },
  { id: "q49", category: "2026 Tournament", question: "Which of these is NOT a 2026 host city?", options: ["Boston", "Houston", "Chicago", "Philadelphia"], answer: "Chicago", explanation: "Chicago did not bid for or receive host city status for 2026.", imagePlaceholder: "/trivia/not-chicago.jpg" },
  { id: "q50", category: "Records", question: "Who won the Best Young Player award at the 2018 World Cup?", options: ["Kylian Mbappé", "Enzo Fernández", "Paul Pogba", "Thomas Müller"], answer: "Kylian Mbappé", explanation: "Mbappé became only the second teenager after Pelé to score in a final.", imagePlaceholder: "/trivia/mbappe2018.jpg" },
  // Batch 2 questions
  { id: "q51", category: "2026 Tournament", question: "Which of these is one of the three official mascots for the 2026 World Cup?", options: ["Zayu the Jaguar", "Striker the Pup", "Fuleco the Armadillo", "Zakumi the Leopard"], answer: "Zayu the Jaguar", explanation: "The 2026 mascots are Zayu (Mexico), Clutch the Bald Eagle (USA), and Maple the Moose (Canada).", imagePlaceholder: "/trivia/mascots2026.jpg" },
  { id: "q52", category: "2026 Tournament", question: "What is the name of the official Adidas match ball for the 2026 tournament?", options: ["Al Rihla", "Trionda", "Jabulani", "Brazuca"], answer: "Trionda", explanation: "Trionda features a design inspired by 'three waves' representing the three host nations.", imagePlaceholder: "/trivia/trionda2.jpg" },
  { id: "q53", category: "Rules", question: "In the new 48-team format, how many 'best third-place teams' advance to the knockouts?", options: ["4", "6", "8", "10"], answer: "8", explanation: "The top 2 from each of the 12 groups advance, plus the 8 best 3rd-place finishers.", imagePlaceholder: "/trivia/third-place.jpg" },
  { id: "q54", category: "History", question: "Which nation has lost the most World Cup finals without ever winning (3 times)?", options: ["Netherlands", "Hungary", "Argentina", "France"], answer: "Netherlands", explanation: "The Dutch reached the final in 1974, 1978, and 2010 but never took home the trophy.", imagePlaceholder: "/trivia/netherlands.jpg" },
  { id: "q55", category: "History", question: "Who was the first player to ever score a hat-trick in a World Cup final?", options: ["Geoff Hurst", "Kylian Mbappé", "Pelé", "Zinedine Zidane"], answer: "Geoff Hurst", explanation: "Hurst scored three for England in the 1966 final. Mbappé became the second in 2022.", imagePlaceholder: "/trivia/hurst.jpg" },
  { id: "q56", category: "2026 Tournament", question: "Which 2026 host city is the furthest north?", options: ["Toronto", "Seattle", "Vancouver", "Boston"], answer: "Vancouver", explanation: "Vancouver (BC Place) is the northernmost venue in the 2026 lineup.", imagePlaceholder: "/trivia/vancouver.jpg" },
  { id: "q57", category: "Records", question: "Which goalkeeper holds the record for most clean sheets in World Cup history (10)?", options: ["Lev Yashin", "Peter Shilton", "Fabien Barthez", "Both Shilton and Barthez"], answer: "Both Shilton and Barthez", explanation: "The Englishman and the Frenchman share the record with 10 shutouts each.", imagePlaceholder: "/trivia/keepers.jpg" },
  { id: "q58", category: "Trivia", question: "What is the 'Golden Ball' award given for?", options: ["Most Goals", "Best Goalkeeper", "Best Player of the Tournament", "Fair Play"], answer: "Best Player of the Tournament", explanation: "While the Golden Boot is for goals, the Golden Ball recognizes the overall best player.", imagePlaceholder: "/trivia/goldenball.jpg" },
  { id: "q59", category: "2026 Tournament", question: "How many total knockout matches will take place in the 2026 tournament?", options: ["16", "32", "24", "12"], answer: "32", explanation: "The new format doubles the knockout stage, starting with a Round of 32.", imagePlaceholder: "/trivia/knockout2026.jpg" },
  { id: "q60", category: "History", question: "In which year did the World Cup feature its first-ever penalty shootout?", options: ["1970", "1982", "1994", "1978"], answer: "1982", explanation: "West Germany beat France in the first shootout in World Cup history.", imagePlaceholder: "/trivia/shootout1982.jpg" },
  { id: "q61", category: "Records", question: "Who is the youngest player to ever play in a World Cup match?", options: ["Pelé", "Norman Whiteside", "Gavi", "Samuel Eto'o"], answer: "Norman Whiteside", explanation: "The Northern Irishman was just 17 years and 41 days old in 1982.", imagePlaceholder: "/trivia/whiteside.jpg" },
  { id: "q62", category: "2026 Tournament", question: "Which Canadian stadium will host matches after a significant capacity expansion?", options: ["BMO Field (Toronto)", "BC Place (Vancouver)", "Olympic Stadium", "Commonwealth Stadium"], answer: "BMO Field (Toronto)", explanation: "BMO Field added thousands of seats to meet FIFA's minimum capacity requirements.", imagePlaceholder: "/trivia/bmo.jpg" },
  { id: "q63", category: "History", question: "Which country won the World Cup the only time it was co-hosted before 2026?", options: ["Brazil", "Germany", "Japan", "South Korea"], answer: "Brazil", explanation: "Brazil won the 2002 World Cup, co-hosted by South Korea and Japan.", imagePlaceholder: "/trivia/brazil2002.jpg" },
  { id: "q64", category: "2026 Tournament", question: "Which team will Mexico face in the opening match at Estadio Azteca on June 11, 2026?", options: ["South Africa", "South Korea", "Czech Republic", "Italy"], answer: "South Africa", explanation: "Mexico kicks off the tournament against South Africa in Group A.", imagePlaceholder: "/trivia/mexvssa.jpg" },
];

/**
 * Get a random selection of N questions from the pool.
 * Ensures a good mix of categories.
 */
export function getRandomQuestions(count = 20): TriviaQuestion[] {
  const shuffled = [...TRIVIA_QUESTIONS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

/**
 * Get all questions NOT in a given set (for the free-play mode).
 */
export function getRemainingQuestions(playedIds: string[]): TriviaQuestion[] {
  return TRIVIA_QUESTIONS.filter(q => !playedIds.includes(q.id))
    .sort(() => Math.random() - 0.5);
}

export const TOTAL_QUESTIONS = TRIVIA_QUESTIONS.length;
export const POINTS_QUESTIONS = 20;
export const FREE_PLAY_QUESTIONS = TOTAL_QUESTIONS - POINTS_QUESTIONS;
export const SECONDS_PER_QUESTION = 7;
