-- ============================================================
-- Migration 069 — Country-follow model.
--
-- Adds a general `countries` reference table (ISO 3166-1 alpha-2, all
-- codes with an existing /public/flags/{code}.svg asset, minus a handful
-- of uninhabited/no-football-federation territories) — NOT the 32-nation
-- World Cup subset already hardcoded in lib/countries.ts, which stays as
-- the WC-specific list it always was.
--
-- Widens user_follows.followed_type to allow 'country' alongside the
-- existing 'team'/'competition' values, and adds competitions.country
-- (nullable text) so a country-follow can be joined against domestic
-- leagues. Backfilling that column for currently-tracked leagues is a
-- separate step later in this same migration (see bottom).
-- ============================================================

create table if not exists public.countries (
  id         uuid default gen_random_uuid() primary key,
  code       text not null unique, -- lowercase FlagBadge/flag.tsx code: ISO 3166-1 alpha-2, or a "gb-xxx" UK-home-nation subdivision code (see below) — matches /public/flags/{code}.svg either way
  name       text not null,
  flag       text not null,        -- flag asset code; own column so callers don't need to assume flag===code
  created_at timestamptz default now()
);

alter table public.countries enable row level security;

create policy "Countries are publicly readable"
  on public.countries for select using (true);

insert into public.countries (code, name, flag) values
  ('af', 'Afghanistan', 'af'),
  ('al', 'Albania', 'al'),
  ('dz', 'Algeria', 'dz'),
  ('as', 'American Samoa', 'as'),
  ('ad', 'Andorra', 'ad'),
  ('ao', 'Angola', 'ao'),
  ('ai', 'Anguilla', 'ai'),
  ('ag', 'Antigua and Barbuda', 'ag'),
  ('ar', 'Argentina', 'ar'),
  ('am', 'Armenia', 'am'),
  ('aw', 'Aruba', 'aw'),
  ('au', 'Australia', 'au'),
  ('at', 'Austria', 'at'),
  ('az', 'Azerbaijan', 'az'),
  ('bs', 'Bahamas', 'bs'),
  ('bh', 'Bahrain', 'bh'),
  ('bd', 'Bangladesh', 'bd'),
  ('bb', 'Barbados', 'bb'),
  ('by', 'Belarus', 'by'),
  ('be', 'Belgium', 'be'),
  ('bz', 'Belize', 'bz'),
  ('bj', 'Benin', 'bj'),
  ('bm', 'Bermuda', 'bm'),
  ('bt', 'Bhutan', 'bt'),
  ('bo', 'Bolivia', 'bo'),
  ('bq', 'Bonaire, Sint Eustatius and Saba', 'bq'),
  ('ba', 'Bosnia and Herzegovina', 'ba'),
  ('bw', 'Botswana', 'bw'),
  ('br', 'Brazil', 'br'),
  ('bn', 'Brunei Darussalam', 'bn'),
  ('bg', 'Bulgaria', 'bg'),
  ('bf', 'Burkina Faso', 'bf'),
  ('bi', 'Burundi', 'bi'),
  ('cv', 'Cabo Verde', 'cv'),
  ('kh', 'Cambodia', 'kh'),
  ('cm', 'Cameroon', 'cm'),
  ('ca', 'Canada', 'ca'),
  ('ky', 'Cayman Islands', 'ky'),
  ('cf', 'Central African Republic', 'cf'),
  ('td', 'Chad', 'td'),
  ('cl', 'Chile', 'cl'),
  ('cn', 'China', 'cn'),
  ('co', 'Colombia', 'co'),
  ('km', 'Comoros', 'km'),
  ('cg', 'Congo', 'cg'),
  ('cd', 'Congo, The Democratic Republic of the', 'cd'),
  ('ck', 'Cook Islands', 'ck'),
  ('cr', 'Costa Rica', 'cr'),
  ('hr', 'Croatia', 'hr'),
  ('cu', 'Cuba', 'cu'),
  ('cw', 'Curaçao', 'cw'),
  ('cy', 'Cyprus', 'cy'),
  ('cz', 'Czechia', 'cz'),
  ('ci', 'Côte d''Ivoire', 'ci'),
  ('dk', 'Denmark', 'dk'),
  ('dj', 'Djibouti', 'dj'),
  ('dm', 'Dominica', 'dm'),
  ('do', 'Dominican Republic', 'do'),
  ('ec', 'Ecuador', 'ec'),
  ('eg', 'Egypt', 'eg'),
  ('sv', 'El Salvador', 'sv'),
  ('gq', 'Equatorial Guinea', 'gq'),
  ('er', 'Eritrea', 'er'),
  ('ee', 'Estonia', 'ee'),
  ('sz', 'Eswatini', 'sz'),
  ('et', 'Ethiopia', 'et'),
  ('fk', 'Falkland Islands (Malvinas)', 'fk'),
  ('fo', 'Faroe Islands', 'fo'),
  ('fj', 'Fiji', 'fj'),
  ('fi', 'Finland', 'fi'),
  ('fr', 'France', 'fr'),
  ('gf', 'French Guiana', 'gf'),
  ('pf', 'French Polynesia', 'pf'),
  ('ga', 'Gabon', 'ga'),
  ('gm', 'Gambia', 'gm'),
  ('ge', 'Georgia', 'ge'),
  ('de', 'Germany', 'de'),
  ('gh', 'Ghana', 'gh'),
  ('gi', 'Gibraltar', 'gi'),
  ('gr', 'Greece', 'gr'),
  ('gl', 'Greenland', 'gl'),
  ('gd', 'Grenada', 'gd'),
  ('gp', 'Guadeloupe', 'gp'),
  ('gu', 'Guam', 'gu'),
  ('gt', 'Guatemala', 'gt'),
  ('gg', 'Guernsey', 'gg'),
  ('gn', 'Guinea', 'gn'),
  ('gw', 'Guinea-Bissau', 'gw'),
  ('gy', 'Guyana', 'gy'),
  ('ht', 'Haiti', 'ht'),
  ('va', 'Holy See (Vatican City State)', 'va'),
  ('hn', 'Honduras', 'hn'),
  ('hk', 'Hong Kong', 'hk'),
  ('hu', 'Hungary', 'hu'),
  ('is', 'Iceland', 'is'),
  ('in', 'India', 'in'),
  ('id', 'Indonesia', 'id'),
  ('ir', 'Iran', 'ir'),
  ('iq', 'Iraq', 'iq'),
  ('ie', 'Ireland', 'ie'),
  ('im', 'Isle of Man', 'im'),
  ('il', 'Israel', 'il'),
  ('it', 'Italy', 'it'),
  ('jm', 'Jamaica', 'jm'),
  ('jp', 'Japan', 'jp'),
  ('je', 'Jersey', 'je'),
  ('jo', 'Jordan', 'jo'),
  ('kz', 'Kazakhstan', 'kz'),
  ('ke', 'Kenya', 'ke'),
  ('ki', 'Kiribati', 'ki'),
  ('kw', 'Kuwait', 'kw'),
  ('kg', 'Kyrgyzstan', 'kg'),
  ('la', 'Laos', 'la'),
  ('lv', 'Latvia', 'lv'),
  ('lb', 'Lebanon', 'lb'),
  ('ls', 'Lesotho', 'ls'),
  ('lr', 'Liberia', 'lr'),
  ('ly', 'Libya', 'ly'),
  ('li', 'Liechtenstein', 'li'),
  ('lt', 'Lithuania', 'lt'),
  ('lu', 'Luxembourg', 'lu'),
  ('mo', 'Macao', 'mo'),
  ('mg', 'Madagascar', 'mg'),
  ('mw', 'Malawi', 'mw'),
  ('my', 'Malaysia', 'my'),
  ('mv', 'Maldives', 'mv'),
  ('ml', 'Mali', 'ml'),
  ('mt', 'Malta', 'mt'),
  ('mh', 'Marshall Islands', 'mh'),
  ('mq', 'Martinique', 'mq'),
  ('mr', 'Mauritania', 'mr'),
  ('mu', 'Mauritius', 'mu'),
  ('yt', 'Mayotte', 'yt'),
  ('mx', 'Mexico', 'mx'),
  ('fm', 'Micronesia, Federated States of', 'fm'),
  ('md', 'Moldova', 'md'),
  ('mc', 'Monaco', 'mc'),
  ('mn', 'Mongolia', 'mn'),
  ('me', 'Montenegro', 'me'),
  ('ms', 'Montserrat', 'ms'),
  ('ma', 'Morocco', 'ma'),
  ('mz', 'Mozambique', 'mz'),
  ('mm', 'Myanmar', 'mm'),
  ('na', 'Namibia', 'na'),
  ('nr', 'Nauru', 'nr'),
  ('np', 'Nepal', 'np'),
  ('nl', 'Netherlands', 'nl'),
  ('nc', 'New Caledonia', 'nc'),
  ('nz', 'New Zealand', 'nz'),
  ('ni', 'Nicaragua', 'ni'),
  ('ne', 'Niger', 'ne'),
  ('ng', 'Nigeria', 'ng'),
  ('nu', 'Niue', 'nu'),
  ('kp', 'North Korea', 'kp'),
  ('mk', 'North Macedonia', 'mk'),
  ('mp', 'Northern Mariana Islands', 'mp'),
  ('no', 'Norway', 'no'),
  ('om', 'Oman', 'om'),
  ('pk', 'Pakistan', 'pk'),
  ('pw', 'Palau', 'pw'),
  ('ps', 'Palestine, State of', 'ps'),
  ('pa', 'Panama', 'pa'),
  ('pg', 'Papua New Guinea', 'pg'),
  ('py', 'Paraguay', 'py'),
  ('pe', 'Peru', 'pe'),
  ('ph', 'Philippines', 'ph'),
  ('pl', 'Poland', 'pl'),
  ('pt', 'Portugal', 'pt'),
  ('pr', 'Puerto Rico', 'pr'),
  ('qa', 'Qatar', 'qa'),
  ('ro', 'Romania', 'ro'),
  ('ru', 'Russian Federation', 'ru'),
  ('rw', 'Rwanda', 'rw'),
  ('re', 'Réunion', 're'),
  ('bl', 'Saint Barthélemy', 'bl'),
  ('sh', 'Saint Helena, Ascension and Tristan da Cunha', 'sh'),
  ('kn', 'Saint Kitts and Nevis', 'kn'),
  ('lc', 'Saint Lucia', 'lc'),
  ('mf', 'Saint Martin (French part)', 'mf'),
  ('pm', 'Saint Pierre and Miquelon', 'pm'),
  ('vc', 'Saint Vincent and the Grenadines', 'vc'),
  ('ws', 'Samoa', 'ws'),
  ('sm', 'San Marino', 'sm'),
  ('st', 'Sao Tome and Principe', 'st'),
  ('sa', 'Saudi Arabia', 'sa'),
  ('sn', 'Senegal', 'sn'),
  ('rs', 'Serbia', 'rs'),
  ('sc', 'Seychelles', 'sc'),
  ('sl', 'Sierra Leone', 'sl'),
  ('sg', 'Singapore', 'sg'),
  ('sx', 'Sint Maarten (Dutch part)', 'sx'),
  ('sk', 'Slovakia', 'sk'),
  ('si', 'Slovenia', 'si'),
  ('sb', 'Solomon Islands', 'sb'),
  ('so', 'Somalia', 'so'),
  ('za', 'South Africa', 'za'),
  ('kr', 'South Korea', 'kr'),
  ('ss', 'South Sudan', 'ss'),
  ('es', 'Spain', 'es'),
  ('lk', 'Sri Lanka', 'lk'),
  ('sd', 'Sudan', 'sd'),
  ('sr', 'Suriname', 'sr'),
  ('se', 'Sweden', 'se'),
  ('ch', 'Switzerland', 'ch'),
  ('sy', 'Syria', 'sy'),
  ('tw', 'Taiwan', 'tw'),
  ('tj', 'Tajikistan', 'tj'),
  ('tz', 'Tanzania', 'tz'),
  ('th', 'Thailand', 'th'),
  ('tl', 'Timor-Leste', 'tl'),
  ('tg', 'Togo', 'tg'),
  ('tk', 'Tokelau', 'tk'),
  ('to', 'Tonga', 'to'),
  ('tt', 'Trinidad and Tobago', 'tt'),
  ('tn', 'Tunisia', 'tn'),
  ('tm', 'Turkmenistan', 'tm'),
  ('tc', 'Turks and Caicos Islands', 'tc'),
  ('tv', 'Tuvalu', 'tv'),
  ('tr', 'Türkiye', 'tr'),
  ('ug', 'Uganda', 'ug'),
  ('ua', 'Ukraine', 'ua'),
  ('ae', 'United Arab Emirates', 'ae'),
  ('gb', 'United Kingdom', 'gb'),
  ('us', 'United States', 'us'),
  ('uy', 'Uruguay', 'uy'),
  ('uz', 'Uzbekistan', 'uz'),
  ('vu', 'Vanuatu', 'vu'),
  ('ve', 'Venezuela', 've'),
  ('vn', 'Vietnam', 'vn'),
  ('vg', 'Virgin Islands, British', 'vg'),
  ('vi', 'Virgin Islands, U.S.', 'vi'),
  ('wf', 'Wallis and Futuna', 'wf'),
  ('eh', 'Western Sahara', 'eh'),
  ('ye', 'Yemen', 'ye'),
  ('zm', 'Zambia', 'zm'),
  ('zw', 'Zimbabwe', 'zw'),
  ('ax', 'Åland Islands', 'ax'),
  -- UK home nations — football fandom (and lib/countries.ts's existing WC
  -- list) treats these as distinct from a generic "United Kingdom" follow.
  ('gb-eng', 'England', 'gb-eng'),
  ('gb-sct', 'Scotland', 'gb-sct'),
  ('gb-wls', 'Wales', 'gb-wls'),
  ('gb-nir', 'Northern Ireland', 'gb-nir')
on conflict (code) do nothing;

-- ── competitions.country ────────────────────────────────────────────────
-- Free-text, matched against countries.name (same "match by name, not FK"
-- convention TRACKED_LEAGUES already uses against competitions.name) —
-- simplest way to join "is this competition's country followed" without
-- a migration to backfill a real countries_id FK across existing rows.
alter table public.competitions add column if not exists country text;

-- ── user_follows.followed_type widen ────────────────────────────────────
alter table public.user_follows drop constraint if exists user_follows_followed_type_check;
alter table public.user_follows add constraint user_follows_followed_type_check
  check (followed_type in ('team', 'competition', 'country'));

-- ── Backfill competitions.country for currently-tracked domestic leagues.
-- Confederation-wide competitions (UCL/UEL/UECL/Libertadores/Sudamericana)
-- deliberately stay null — they don't belong to one country.
update public.competitions set country = 'England'  where name = 'Premier League';
update public.competitions set country = 'Spain'    where name = 'La Liga';
update public.competitions set country = 'Italy'    where name = 'Serie A';
update public.competitions set country = 'Germany'  where name = 'Bundesliga';
update public.competitions set country = 'France'   where name = 'Ligue 1';
update public.competitions set country = 'United States' where name = 'MLS';
update public.competitions set country = 'Brazil'   where name = 'Brazil Serie A';
update public.competitions set country = 'Israel'   where name = 'Ligat Ha''al';
