-- ============================================================
-- Migration 073 — Match Recaps
-- ============================================================
-- Short, factual, auto-generated recap paragraphs for finished matches,
-- synthesized from matches.match_events (goals/cards/final score) only —
-- never speculative. Generated by a dedicated cron
-- (app/api/recaps/route.ts, lib/services/match-recaps.ts) via the
-- Anthropic API, same convention as Oracle predictions (migration 057)
-- but a distinct feature/table — a recap summarizes what already
-- happened, it doesn't predict anything.

create table if not exists public.match_recaps (
  id            uuid primary key default gen_random_uuid(),
  match_id      text not null unique references public.matches(id) on delete cascade,
  recap_text    text not null,
  model         text not null,
  generated_at  timestamptz not null default now()
);

alter table public.match_recaps enable row level security;

create policy "Anyone can read match recaps"
  on public.match_recaps for select
  using (true);

-- Written only by the recap generation cron (service role) — same
-- convention as oracle_predictions and points_snapshots.
create policy "Service role manages match recaps"
  on public.match_recaps for insert
  with check (false);

create policy "Service role updates match recaps"
  on public.match_recaps for update
  using (false);
