import { NextRequest, NextResponse } from "next/server";
import { TRANSLATIONS, localeFromLanguageCode } from "@/lib/i18n";
import { sbAdmin } from "@/lib/supabase/admin";

async function sendMessage(chatId: number | string, text: string) {
  const token = process.env.TELEGRAM_BOT_TOKEN!;
  await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
    method:  "POST",
    headers: { "Content-Type": "application/json" },
    body:    JSON.stringify({ chat_id: chatId, text, parse_mode: "HTML" }),
  });
}

interface TelegramUpdate {
  message?: {
    chat:  { id: number };
    text?: string;
    from?: { id: number; first_name?: string; language_code?: string };
  };
}

export async function POST(req: NextRequest) {
  // Telegram sets this header on every webhook delivery when a secret_token
  // was registered via setWebhook — without it, anyone who finds this URL
  // could POST fabricated /start payloads directly.
  const expectedSecret = process.env.TELEGRAM_WEBHOOK_SECRET;
  if (expectedSecret) {
    const gotSecret = req.headers.get("x-telegram-bot-api-secret-token");
    if (gotSecret !== expectedSecret) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
  }

  let update: TelegramUpdate;
  try {
    update = await req.json() as TelegramUpdate;
  } catch {
    return NextResponse.json({ ok: true });
  }

  const message = update.message;
  if (!message) return NextResponse.json({ ok: true });

  const chatId = message.chat.id;
  const text   = message.text ?? "";
  const t      = TRANSLATIONS[localeFromLanguageCode(message.from?.language_code)];

  if (text.startsWith("/start")) {
    // Deep link payload: /start <one-time link token> — generated by
    // POST /api/telegram/link-token, NOT the profile id (see migration 047:
    // the raw id was guessable/enumerable and let anyone redirect another
    // user's Telegram notifications to their own chat).
    const parts = text.trim().split(" ");
    const token = parts[1] ?? null;

    if (token) {
      const { data: profile } = await sbAdmin()
        .from("profiles")
        .select("id, telegram_link_token_expires_at")
        .eq("telegram_link_token", token)
        .maybeSingle();

      const expired = !profile?.telegram_link_token_expires_at
        || new Date(profile.telegram_link_token_expires_at as string).getTime() < Date.now();

      if (!profile || expired) {
        await sendMessage(chatId, t.notif_bot_expired);
        return NextResponse.json({ ok: true });
      }

      const { error } = await sbAdmin()
        .from("profiles")
        .update({
          telegram_chat_id: String(chatId),
          telegram_link_token: null,
          telegram_link_token_expires_at: null,
          telegram_language_code: message.from?.language_code ?? null,
        })
        .eq("id", profile.id as string);

      if (error) {
        await sendMessage(chatId, t.notif_bot_link_error);
        return NextResponse.json({ ok: true });
      }

      await sendMessage(chatId, t.notif_bot_connected);
    } else {
      await sendMessage(chatId, t.notif_bot_welcome);
    }

    return NextResponse.json({ ok: true });
  }

  // Any other message
  await sendMessage(chatId, t.notif_bot_fallback);
  return NextResponse.json({ ok: true });
}
